language: ruby
bundler_args: "--without debug"
before_script:
- "./spec/setup/arangodb.sh"
rvm:
- 1.9.3
- 2.0.0
- 2.1.2
- jruby-19mode
- jruby-head
- ruby-head
env:
- ARANGODB_DISABLE_AUTHENTIFICATION=true VERSION=2.2
matrix:
  allow_failures:
  - rvm: jruby-19mode
  - rvm: ruby-head
  - rvm: jruby-head
script: bundle exec rake ci
addons:
  code_climate:
    repo_token: cd5dd119d022e5b0d4fda98d25aa93473ed5b580c3f621475c3e605a858f5790
notifications:
  slack:
    secure: H8F0Eo0dc0uP0kh4Wm4D6kDuDeEQrjTotUpz2n4Ls8errJp0r0C9CbXrRE574B1VeZF/tBzm9IUx4wDRuR2xaYfIww5gJTz2+RKp+thgspz8L3KW5nuLttxzqp8cNP2b9Gedj72nTebQK3gEt7v/HFgo9lg2QSEvZ4n7zYFkmIc=
